### ISSUE TITLE
Installing eblot/armeabi/arm-none-eabi-gcc failed

### ISSUE THREAD

**Issue by kjrkjr** [eblot/homebrew-armeabi#5] opened 2019-02-12 20:04 UTC
patching file gcc/graphite.h
==> ../configure --build=x86_64-apple-darwin18.2.0 --prefix=/usr/local/Cellar/gcc/8.2.0 --libdir=/usr/local/Cellar/gcc/8.2.0/lib/gcc/8 --disable-nls --enable-checking=release --enable-languages=c,c
==> make BOOT_LDFLAGS=-Wl,-headerpad_max_install_names
==> make install
🍺  /usr/local/Cellar/gcc/8.2.0: 1,413 files, 287.5MB, built in 60 minutes 22 seconds
==> Installing eblot/armeabi/arm-none-eabi-gcc
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-7.3.0/gcc-7.3.0.tar.xz
==> Downloading from http://gra.mirror.cyberbits.eu/gnu/gcc/gcc-7.3.0/gcc-7.3.0.tar.xz
######################################################################## 100.0%
==> Downloading ftp://sourceware.org/pub/newlib/newlib-3.0.0.tar.gz
######################################################################## 100.0%
==> ditto /private/tmp/arm-none-eabi-gcc--newlib-20190212-47310-1eloun2/newlib-3.0.0/newlib /private/tmp/arm-none-eabi-gcc-20190212-47310-ggxqqg/gcc-7.3.0/newlib
==> /private/tmp/arm-none-eabi-gcc-20190212-47310-ggxqqg/gcc-7.3.0/configure --prefix=/usr/local/Cellar/arm-none-eabi-gcc/7.3.0 --target=arm-none-eabi --disable-shared --with-gnu-as --with-gnu-ld -
==> mkdir -p /usr/local/Cellar/arm-none-eabi-gcc/7.3.0/arm-none-eabi/lib/fpu/interwork
==> make
Last 15 lines from /Users/kjaffres/Library/Logs/Homebrew/arm-none-eabi-gcc/04.make:
   unsigned dims = isl_space_dim (space, isl_dim_set);
                   ^~~~~~~~~~~~~
                   isl_aff_dim
/private/tmp/arm-none-eabi-gcc-20190212-47310-ggxqqg/gcc-7.3.0/gcc/graphite-optimize-isl.c:60:3: error: 'isl_space_free' was not declared in this scope
   isl_space_free (space);
   ^~~~~~~~~~~~~~
make[2]: *** [graphite-dependences.o] Error 1
/private/tmp/arm-none-eabi-gcc-20190212-47310-ggxqqg/gcc-7.3.0/gcc/graphite-optimize-isl.c:60:3: note: suggested alternative: 'isl_aff_free'
   isl_space_free (space);
   ^~~~~~~~~~~~~~
   isl_aff_free
make[2]: *** [graphite-optimize-isl.o] Error 1
rm gcc.pod
make[1]: *** [all-gcc] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/eblot/homebrew-armeabi/issues

**Comment by kjrkjr** [comment] 2019-02-12 20:06
I've tried to install the ARM gcc on macos mojave - Anyone with the same experience?

**Comment by eblot** [comment] 2019-02-15 08:10
I do not actively maintain GCC for ARM-EABI for a while, since I've only been using clang for several years.

However I have no trouble to build GCC 7.4.0 (just checked). Looks like the nth iteration of issues with ISL, which has been a recurrent source of build troubles for about ... 10 years.

Which version of ISL is installed on your system?

**Comment by eblot** [comment] 2019-11-25 10:21
No feedback, not reproducible, closing.

**Closed as completed by eblot** 2019-11-25 10:21 UTC
